sudo: false
language: go

go:
  - 1.x
env:
  - DB=mysql
  # - DB=postgresql

matrix:
  fast_finish: true

install:
  - # Do nothing. This is needed to prevent default install action "go get -t -v ./..." from happening here (we want it to happen inside script step).

before_script:
# - sh -c "if [ '$DB' = 'postgresql' ]; then psql -c 'CREATE DATABASE tests;' -U postgres; psql -U postgres -d tests -a -f tests/migration.psql.sql; fi"
# - sh -c "if [ '$DB' = 'mysql' ]; then  mysql -e 'CREATE DATABASE tests;';mysql -uroot tests < tests/migration.mysql.sql; fi"


script:
  - go get -t -v ./...
  - # diff -u <(echo -n) <(gofmt -d -s .) ignored because of helper_internal_test.go and helper_test.go
  - go vet .
  - go test -v -p 1 -race ./... -coverprofile=coverage.txt -covermode=atomic

after_success:
  - if [ $DB == "mysql" ]; then bash <(curl -s https://codecov.io/bash);fi
#- if [ $DB == "postgresql" ]; then bash <(curl -s https://codecov.io/bash) -cF postgresql;fi
